#!/bin/bash

if [ "$@" == "user list --sudo" ]
then
        echo $SUDO_USER
        exit
fi


if [ "$1" == "file" ] && [ "$2" == "getinfo" ] && [ "$3" == "hello.txt" ]
then
        stat hello.txt
fi



if [ "$1" == "cpu" ] && [ "$2" == "getinfo" ]
then
       lscpu
fi

if [ "$1" == "memory" ] && [ "$2" == "getinfo" ]
then
       free
fi

if  [ "$1" == "--help" ]
then
       echo " Display information about command.

    Displays brief summaries of builtin commands. If PATTERN IS
    specified, gives detailed help on all commands matching PATTERN,
    otherwise the list of help topics is printed.
 "
fi

if [ "$1" == "--version" ]
then
       echo "v0.1.0"
fi


if [ "$1" == "user" ] && [ "$2" == "list" ]
then
        cat /etc/passwd
        exit
fi

if [ $(id -u) -eq 0 ] && [ "$1" == "user" ] && [ "$2" == "create" ]
then
        read -p "Enter username : " username
        read -s -p "Enter password : " password
        egrep "^$username" /etc/passwd >/dev/null
        if [ $? -eq 0 ]; then
                echo "$username exists!"
                exit 1
        else
                pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
                useradd -m -p "$pass" "$username"
                [ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
        fi
else
        exit 2
fi
